### ISSUE TITLE
deep linking crash for referringApplication

### ISSUE THREAD

**Issue by amrgetment** [segmentio/analytics_flutter#133]
In deep linking, I get an error here

in state.g.dart
DeepLinkData _$DeepLinkDataFromJson(Map<String, dynamic> json) => DeepLinkData(
     ` json['referringApplication'] as String,`

```
I/flutter ( 7119): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 7119): type 'Null' is not a subtype of type 'String' in type cast
I/flutter ( 7119): 
I/flutter ( 7119): #0      _$DeepLinkDataFromJson (package:segment_analytics/state.g.dart:38:36)
I/flutter ( 7119): #1      new DeepLinkData.fromJson (package:segment_analytics/state.dart:369:7)
I/flutter ( 7119): #2      Analytics._onStateReady.<anonymous closure> (package:segment_analytics/analytics.dart:93:44)
I/flutter ( 7119): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
I/flutter ( 7119): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
I/flutter ( 7119): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
I/flutter ( 7119): #6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
I/flutter ( 7119): #7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
I/flutter ( 7119): #8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
I/flutter ( 7119): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
I/flutter ( 7119): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
I/flutter ( 7119): #11     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
I/flutter ( 7119): #12     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
I/flutter ( 7119): #13     _Pending
```

did I do something wrong to make `referringApplication` null?

**Comment by MichaelGHSeg** [comment]
This should also be fixed in the next update, which will be as soon as I can get testing completed and fully verify it.

**Comment by amrgetment** [comment]
I wonder if there is a way to add that value or what exactly is referringApplication field

**Comment by MichaelGHSeg** [comment]
It's the application ID for the app that sent the link ID, such as the web browser.  I've now tested that events can be received without that value present, should be out soon.

**Comment by MichaelGHSeg** [comment]
Soon unfortunately means first thing next year, due to a soft code freeze. Sorry for the misinformation😓.

**Comment by amrgetment** [comment]
no worries

**Comment by MichaelGHSeg** [comment]
Latest release should fix the issue, let us know if you have any more issues.  Cheers!

**Comment by amrgetment** [comment]
thanks a lot
